basic:
  workdir : /global/cscratch1/sd/sws/dc2/data/cosmoDC2_v1.0_small/desy5/
  simulation : cosmoDC2_v1.0_small
  columns : ra dec mag_r_lsst mag_i_lsst mag_z_lsst mag_true_r_lsst mag_true_i_lsst mag_true_z_lsst redshift
  cuts : mag_i_lsst,24.1,- mag_r_lsst,22.5,- redshift,0.2,+ redshift,0.75,-
  colour_split : red
  sample : lens

nofz:
  zbins : 5
  sigma : 0.01


2pt:
  tbins : 10
  tmin : 0.1
  tmax : 250
  ctype : position